//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLatestProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        [Display(Name = "User No")]
        public string UserNo { get; set; }
        [Display(Name ="First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Middle Name")]
        public string MiddleName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        public string Gender { get; set; }
        [Display(Name = "Date Of Birth")]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Position { get; set; }
        [Display(Name = "Marital Status")]
        public string MaritalStatus { get; set; }
        public Nullable<double> Salary { get; set; }
        [Display(Name = "Hire Date")]
        public Nullable<System.DateTime> HireDate { get; set; }
        [Display(Name = "Employee Type")]
        public string EmployeeType { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        [Display(Name = "Photo")]
        public string ImagePath { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        [Display(Name = "Education Level")]
        public Nullable<int> EducationLevelID { get; set; }
        [Display(Name = "Field Of Study")]
        public Nullable<int> FieldOfStudyID { get; set; }
        [Display(Name ="Department Name")]
        public Nullable<int> DepartmentID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
        public virtual FieldOfStudy FieldOfStudy { get; set; }
    }
}
