//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLatestProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkList
    {
        public int MarkListID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string Sesmester { get; set; }
        public Nullable<System.DateTime> AcademicYear { get; set; }
        public Nullable<double> Mark { get; set; }
    
        public virtual TblCours TblCours { get; set; }
        public virtual Student Student { get; set; }
    }
}
