//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLatestProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Admissions = new HashSet<Admission>();
            this.MarkLists = new HashSet<MarkList>();
        }
    
        public int StudentID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Grade { get; set; }
        public string Section { get; set; }
        public Nullable<int> Telephone { get; set; }
        public string ParentFirstName { get; set; }
        public string ParentmiddleName { get; set; }
        public string ParentLastName { get; set; }
        public string ParentTelephone { get; set; }
        public string Subcity { get; set; }
        public string Wereda { get; set; }
        public string Kebelle { get; set; }
        public string HouseNo { get; set; }
        [Display(Name ="Photo")]
        public string ImagePhath { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission> Admissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarkList> MarkLists { get; set; }
    }
}
